[tool.poetry]
name = "units"
version = "0.1.0"
description = ""
authors = ["M4tus4l3m <lucas.sievers@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
